### ISSUE TITLE
WRT: execve flag 

### ISSUE THREAD

**Issue by rdebath** [vivier/qemu-m68k#11]
Commit  [8952fce8 "linux-user: add option to intercept execve() syscalls"](https://github.com/vivier/qemu-m68k/commit/8952fce860f0eebc61e1ba665c48f76a7585ebf4) adds the ability to specify that only this copy of the QEMU executable will be used for execve.

It has some issues:
- It doesn't pass on the option to exec'd programs. 
- If you just set the environment variable (and use binfmt misc) it fails with a very weird error.
- It can't run SUID executables.

I'm using this patch to work around some of this buy simply putting the path to the exe in the variable, however, it's not complete as I have to turn it off for SUID executables.

There are several ways this could be worked (all the way up to fakeroot/fakechroot support) but as I have solved my immediate problem (Which was to prevent x86 static executables running) it seemed best to just report this.

``` patch
diff --git a/linux-user/main.c b/linux-user/main.c
index 7c71b72..f7f6268 100644
--- a/linux-user/main.c
+++ b/linux-user/main.c
@@ -4081,6 +4081,16 @@ static void handle_arg_execve(const char *arg)
     char *ret;
     int len;

+    if (arg && *arg)
+    {
+        ret = realpath(arg, buf);
+
+        if (ret != NULL) {
+            qemu_execve_path = strdup(buf);
+            return;
+        }
+    }
+
     /* try getauxval() */
     execfn = (const char *) getauxval(AT_EXECFN);

```

**Comment by vivier** [comment]
8952fce8 "linux-user: add option to intercept execve() syscalls" has never been merged
