### ISSUE TITLE
Unsupported syscall: 352

### ISSUE THREAD

**Issue by glaubitz** [vivier/qemu-m68k#4]
When installing/updating a recent version of udev on Debian, qemu complains about an unsupported syscall, namely 352:

Setting up udev (228-4+b1) ...
qemu: Unsupported syscall: 352
addgroup: The group `input' already exists as a system group. Exiting.

Adrian

**Comment by vivier** [comment]
Syscall 352 is getrandom(), and it is not implemented by qemu. It should be easy to add.

**Comment by glaubitz** [comment]
I will have a look at it later. I just added it here so we don't forget it :).

**Comment by vivier** [comment]
While I was playing with debian unstable, I have implemented this syscall, see branch 680x0-master-dev.

https://github.com/vivier/qemu-m68k/commit/2aa75e8188ac0eaca13bfad044021162be88a579

**Comment by glaubitz** [comment]
Ah, nice. Thanks a lot!

**Comment by glaubitz** [comment]
This seems to work. Should we close this issue?
