### ISSUE TITLE
Report the selected CPU in the bootinfo for the m68k machine + add a way to pass 68000, 68010 via boot info?

### ISSUE THREAD

**Issue by fifteenhex** [vivier/qemu-m68k#51]
Hi,

I used your virt machine with 68000 selected to revive the linux 68000 support.
I have a port of u-boot that runs on the 68000 too and creates a device tree from the bootinfo.
The sticking point I have right now is to make my 68000 enabled kernel boot on any 68k I need to patch some interrupt handling stuff to handle the vector/frame type field missing. 

If the virt machine could report the select cpu via the bootinfo (it's always 68040 right now) I could flip which cpu is used and test my code works. But it seems like bootinfo doesn't actually have flags for 68000 or 68010 so I'm not sure what we would do there.

Thanks!

**Comment by vivier** [comment]
Hi @fifteenhex 
as the machine is merged in upstream Qemu you should use the main Qemu bug tracker.
https://gitlab.com/qemu-project/qemu/-/issues
The value of bootinfo can be set according the parameters given to Qemu. It was not needed until now, it's why we use always 68040, moreover other CPU models are less tested and I think some features can be missing.

**Comment by fifteenhex** [comment]
> Hi @fifteenhex as the machine is merged in upstream Qemu you should use the main Qemu bug tracker. https://gitlab.com/qemu-project/qemu/-/issues The value of bootinfo can be set according the parameters given to Qemu. It was not needed until now, it's why we use always 68040, moreover other CPU models are less tested and I think some features can be missing.

Awesome, I'll open a bug there. The virt machine with 68000 is running nommu linux with virtio io etc working so I think it's pretty close. I seem to remember there being some m68k testkit thing too? Anyhow thanks for the input.
